#!/usr/bin/env bash
# vim: set ft=ruby:

# This file executes as a bash script, which turns around and executes Ruby via
# the line below. The -x argument to Ruby makes it discard everything before
# the second "!ruby" shebang. This allows us to work on Linux, where the
# shebang can only have one argument so we can't directly say
# "#!/usr/bin/env ruby --disable-gems". Thanks for that, Linux.
#
# If this seems confusing, don't worry. You can treat it as a normal Ruby file
# starting with the "!ruby" shebang below.
# - Gary

exec /usr/bin/env ruby --disable-gems -x "$0" $*
#!ruby

Array(1..5).reverse.each do |n|
  system("clear && printf '\e[3J'")
  system("cat bwlogo.txt")
  puts "#{n}..."
  sleep 0.75
end
puts "LIFT OFF"

# Install RVM

# Install Ruby

# Install Homebrew

